const users = [
  {
    name: "Gustav Christensen",
    username: "ticklishsnake376",
    email: "gustav.christensen@example.com",
    Gender: "M",
    profile: "https://randomuser.me/api/portraits/men/90.jpg",
    address: "2745 Nellikevej, \u00d8ster Assels, Hovedstaden",
    origin: "DK",
  },
  {
    name: "Naomi da Luz",
    username: "redleopard386",
    email: "naomi.daluz@example.com",
    Gender: "F",
    profile: "https://randomuser.me/api/portraits/women/60.jpg",
    address: "1057 Travessa dos A\u00e7orianos, Francisco Morato, Alagoas",
    origin: "BR",
  },
  {
    name: "Frank-Michael Nehring",
    username: "tinycat892",
    email: "frank-michael.nehring@example.com",
    Gender: "M",
    profile: "https://randomuser.me/api/portraits/men/31.jpg",
    address: "6162 Ahornweg, Geestland, Sachsen",
    origin: "DE",
  },
  {
    name: "Angelien Stoter",
    username: "brownsnake874",
    email: "angelien.stoter@example.com",
    Gender: "F",
    profile: "https://randomuser.me/api/portraits/women/48.jpg",
    address: "103 Biezenhaak, Asselt, Noord-Brabant",
    origin: "NL",
  },
  {
    name: "Josef Singh",
    username: "lazywolf827",
    email: "josef.singh@example.com",
    Gender: "M",
    profile: "https://randomuser.me/api/portraits/men/94.jpg",
    address: "6321 Trygve Ryens vei, Eidfjord, Telemark",
    origin: "NO",
  },
  {
    name: "Maude Guerin",
    username: "orangegorilla999",
    email: "maude.guerin@example.com",
    Gender: "F",
    profile: "https://randomuser.me/api/portraits/women/38.jpg",
    address: "7295 Rue Louis-Garrand, Gr\u00f4ne, Solothurn",
    origin: "CH",
  },
  {
    name: "Sara Shelton",
    username: "orangemeercat379",
    email: "sara.shelton@example.com",
    Gender: "F",
    profile: "https://randomuser.me/api/portraits/women/28.jpg",
    address: "5780 Taylor St, Cairns, Queensland",
    origin: "AU",
  },
  {
    name: "M\u00e1rcio Carvalho",
    username: "biglion541",
    email: "marcio.carvalho@example.com",
    Gender: "M",
    profile: "https://randomuser.me/api/portraits/men/13.jpg",
    address:
      "5117 Travessa dos Mart\u00edrios, Feira de Santana, Mato Grosso do Sul",
    origin: "BR",
  },
  {
    name: "Jake Ellis",
    username: "silverswan928",
    email: "jake.ellis@example.com",
    Gender: "M",
    profile: "https://randomuser.me/api/portraits/men/88.jpg",
    address: "7316 North Road, Mullingar, Westmeath",
    origin: "IE",
  },
  {
    name: "Nalan Ke\u00e7eci",
    username: "sadtiger854",
    email: "nalan.kececi@example.com",
    Gender: "F",
    profile: "https://randomuser.me/api/portraits/women/46.jpg",
    address: "692 Fatih Sultan Mehmet Cd, Kocaeli, Elaz\u0131\u011f",
    origin: "TR",
  },
  {
    name: "Syed Haugen",
    username: "organicmeercat819",
    email: "syed.haugen@example.com",
    Gender: "M",
    profile: "https://randomuser.me/api/portraits/men/57.jpg",
    address: "8859 Alunsj\u00f8veien, Skj\u00f8nhaug, Hedmark",
    origin: "NO",
  },
  {
    name: "Lionel Holler",
    username: "ticklishfrog543",
    email: "lionel.holler@example.com",
    Gender: "M",
    profile: "https://randomuser.me/api/portraits/men/21.jpg",
    address: "8951 Am Sportplatz, Marktleuthen, Sachsen-Anhalt",
    origin: "DE",
  },
  {
    name: "Andrew Duval",
    username: "greenwolf358",
    email: "andrew.duval@example.com",
    Gender: "M",
    profile: "https://randomuser.me/api/portraits/men/29.jpg",
    address: "5119 Rue de L'Abbaye, Bauen, Uri",
    origin: "CH",
  },
  {
    name: "Enrique Montero",
    username: "purpleswan155",
    email: "enrique.montero@example.com",
    Gender: "M",
    profile: "https://randomuser.me/api/portraits/men/35.jpg",
    address: "289 Calle de Toledo, La Coru\u00f1a, Castilla y Le\u00f3n",
    origin: "ES",
  },
  {
    name: "Leslie Simmmons",
    username: "organicrabbit755",
    email: "leslie.simmmons@example.com",
    Gender: "F",
    profile: "https://randomuser.me/api/portraits/women/87.jpg",
    address: "8632 Fairview St, Milwaukee, Vermont",
    origin: "US",
  },
  {
    name: "John Lee",
    username: "goldenladybug822",
    email: "john.lee@example.com",
    Gender: "M",
    profile: "https://randomuser.me/api/portraits/men/52.jpg",
    address: "6556 Wheeler Ridge Dr, Cairns, New South Wales",
    origin: "AU",
  },
  {
    name: "Tamara Hall",
    username: "crazyfrog265",
    email: "tamara.hall@example.com",
    Gender: "F",
    profile: "https://randomuser.me/api/portraits/women/6.jpg",
    address: "5273 Marsh Ln, Bendigo, New South Wales",
    origin: "AU",
  },
  {
    name: "Vitus D\u00f6hler",
    username: "ticklishpeacock134",
    email: "vitus.dohler@example.com",
    Gender: "M",
    profile: "https://randomuser.me/api/portraits/men/93.jpg",
    address: "4730 Meisenweg, Mahlberg, Saarland",
    origin: "DE",
  },
  {
    name: "Vildan Akg\u00fcl",
    username: "greengorilla956",
    email: "vildan.akgul@example.com",
    Gender: "F",
    profile: "https://randomuser.me/api/portraits/women/68.jpg",
    address: "7860 Vatan Cd, \u00c7anakkale, K\u00fctahya",
    origin: "TR",
  },
];

export default users;